name: todo_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.1
  dartz: ^0.10.1
  rxdart: ^0.27.7
  provider: ^6.0.5
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  dio: ^5.1.1
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
